name: terraform-modules

on:
  push:

jobs:
  validate:
    name: 'validate terraform modules'
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        module:
          - aws_s3_remote_backend

    steps:
      - name: 'checkout'
        uses: actions/checkout@v2

      - name: 'aws: configure'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.CICD_PIPELINE_REMOTE_BACKEND_ROLE_ARN }}
          aws-region: ap-southeast-1

      - name: 'tf: setup'
        uses: hashicorp/setup-terraform@v2

      - name: 'tf: format'
        id: fmt
        working-directory: ${{ matrix.module }}
        run: terraform fmt -check -recursive

      - name: 'tf: init'
        id: init
        working-directory: ${{ matrix.module }}
        run: terraform init

      - name: 'tf: validate'
        id: validate
        working-directory: ${{ matrix.module }}
        run: terraform validate

      - name: 'tf: plan'
        id: plan
        working-directory: examples/${{ matrix.module }}
        run: |
          terraform init
          terraform plan

  create-release:
    if: contains(github.ref, 'refs/heads/main')
    needs: validate

    name: 'create-release'
    runs-on: ubuntu-latest 

    steps:
      - name: 'checkout'
        uses: actions/checkout@v2

      - uses: google-github-actions/release-please-action@v3.1.2
        with:
          token: ${{ secrets.CICD_PIPELINE_GITHUB_TOKEN }}
          release-type: node



  